In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [5]:
for p in widenet.named_parameters():
    print(type(p))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


# Peeking inside the network

In [8]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[ 0.0198,  0.4679],
        [-0.6307, -0.1229]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.1086, -0.0744], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.0426, -0.3482],
        [ 0.1339,  0.0575]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.5444,  0.3240], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.4537,  0.3839],
        [ 0.6974,  0.2740],
        [-0.3194, -0.4769]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.5723,  0.0689,  0.0881], requires_grad=True))
 


In [9]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [14]:
# just the parameters
#help(torch.nn.parameter.Parameter)
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[-0.7008,  0.5092],
        [-0.4114, -0.6194],
        [ 0.1391, -0.3437],
        [-0.5843,  0.5447]], requires_grad=True)
 
Parameter containing:
tensor([-0.2675, -0.4759,  0.4322, -0.6468], requires_grad=True)
 
Parameter containing:
tensor([[ 0.0377,  0.0312,  0.0524, -0.1593],
        [-0.4180, -0.2917, -0.1061, -0.3675],
        [-0.2227, -0.0051, -0.0941,  0.2769]], requires_grad=True)
 
Parameter containing:
tensor([ 0.1215, -0.0146,  0.3051], requires_grad=True)
 


In [7]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [15]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [ ]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!